### ISSUE TITLE
[Solved] Gets disconnected after few hours

### ISSUE THREAD

**Issue by TheSlackOne** [awslabs/aws-web3-ws-provider#3]
My connection keeps disconnecting after few hours. No reason or message. Something I could try like _keep alive_?

Now trying this. Will report if the keepalive flags work.
```
Web3(new AWSWebsocketProvider(process.env.AMB_WS_ENDPOINT, {
    clientConfig: {
      credentials: credentials,
      keepalive: true,
      keepaliveInterval: 60000  // ms.
    },
    reconnect: {
      auto: true,
      delay: 5000, // ms
      maxAttempts: 5,
      onTimeout: false
    }
  }));
```

**Comment by cayblood** [comment]
I suggest taking this up with AWS business support. The problem is more likely to be some configuration setting or issue with the AMB service than with this library.

**Comment by TheSlackOne** [comment]
Working so far, that appears to have it fixed. Without the above setup the connection lasts ~3 hours.
